# Generated by Django 5.0.6 on 2024-05-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField()),
                ('Title', models.CharField()),
                ('Year', models.IntegerField()),
                ('Length', models.CharField()),
                ('Rating', models.CharField()),
            ],
        ),
    ]
